<html>
    <head>
    <head>
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script src ="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    </head> 
    <body>
        <div class="container">
            <div class="row pull-right"> 
                <a class="twitter-share-button" 
                   href="http://api.twitter.com/1/"
                   >
                    Tweet
                </a>
            </div>
        </div>
        <script type="text/javascript">
            !function (d, s, id) {
                var js, fjs = d.getElementsByTagName(s)[0];
                if (!d.getElementById(id)) {
                    js = d.createElement(s);
                    js.id = id;
                    js.src = "http://platform.twitter.com/anywhere.js?id=" + gTWApplicationId;
                    fjs.parentNode.insertBefore(js, fjs);
                }
            }(document, "script", 'twitter-anywhere');
//describe the login actions  
            twttr.anywhere(function (T) {
                T.bind("authComplete", function (e, user) {
                    var token = user.attributes._identity;
                    //define the login function on your client through Twitter  
                });
            });
//function we link to the click on the custom login button through Twitter  
            function doTWSignIn() {
                twttr.anywhere(function (T) {
                    T.signIn();
                });
            }
        </script> 

    </body>
</html>
