<?php
$auth = Zend_Auth::getInstance();
$storage = $auth->getStorage();
$sessionRead = $storage->read();
if (empty($sessionRead)) {
    ?>

<?php if($this->error){ echo $this->error;}?>


<html>
    <head>
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
      <link rel="stylesheet" href="style.css">
 		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
 		<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
                <style>
                       
                    .div{
                        
                        width:100px;
                    }    
                    
                    
                </style>
    
    </head>
<div class="container form"> 
         <div class="row">
         <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-primary ">
   <div class="panel-heading" id="alert">
      <h3 class="panel-title">Sign up</h3>
   </div>
   <div class="panel-body">





<?php
echo $this->form;
?>
</div>
           </div>
       </div>
      </div>
</div>
</html>
 <?php
} else {
    header("Location: http://localhost/The-A-Team/public/home/home");
}
?>
