<?php
$auth = Zend_Auth::getInstance();
$storage = $auth->getStorage();
$sessionRead = $storage->read();
$type = $sessionRead->type;
if ($type != "Admin") {
    ?>
    <html>
        <head>


            <style>
                .edit{
                    margin-top: 50px;
                    margin-right: 50px;
                    width:100px;
                    height:100px;

                    float:right;
                }
                .name{
                    margin-top: 50px;
                    margin-right: 650px;
                    width:100px;
                    height:100px;

                    float:right; 

                }


            </style>
        </head>
        <?php
        for ($i = 0; $i < count($this->user); $i++) {
            //unset($this->user[$i]['password']);
            //unset($this->user[$i]['active']);
            //unset($this->user[$i]['facebookid']);
//foreach ($this->user[$i] as $key=>$value):
            //if($key=='image' || $key=='type' || $key=='id')continue;
            ?>
            <div class="container">
                <div class="row">
                    <p><h1 class="title"> My Profile </h1></p><hr>
                    <img src="../../public/images/users/<?php echo $this->user[$i]['image']; ?>" class="img-circle" height="200px" width="200px">
                    <?php
                    if (!$this->user[$i]['facebookid']) {
                        ?>
                        <div class="edit"><a href="<?php echo $this->baseUrl() ?>/Users/edit/id/<?php echo $this->user[$i]['id']; ?>"class="btn btn-info btn-lg" id="alert">Edit</a>
                        </div>
                        <?php
                    }
                    ?>
                    <div class="name"><h1><?php echo $this->user[$i]['name']; ?></h1></div>
                </div>
                <div class="row">
                    <div class="panel panel-primary  col-md-5 col-md-offset-3">
                        <div class="panel-heading" id="alert">
                            <h3 class="panel-title">About</h3>
                        </div>

                        <div class="panel-body">

                            <p><h3 class="title"> Email: </h3> <?php echo $this->user[$i]['email']; ?> </p>
                            <p><h3 class="title"> Gender: </h3> <?php echo $this->user[$i]['gender']; ?> </p>
                            <p><h3 class="title"> Country: </h3> <?php echo $this->user[$i]['country']; ?> </p>
                            <p><h3 class="title"> Type: </h3> <?php echo $this->user[$i]['type']; ?> </p>


                        </div>
                    </div>
                </div>


                        <!--<img src="../../public/images/users/<?php echo $this->user[$i]['image']; ?>">-->
            <?php } ?>
            <div class="container">
                <div class="panel panel-primary col-md-3 pull-right" >
                    <div class="panel-heading" id="alert">
                        <h3 class="panel-title ">Courses</h3>
                    </div>
                    <div class="panel-body">
                        <?php if ($this->usercourse) { ?>
                            <?php
                            for ($i = 0; $i < count($this->usercourse); $i++) {

                                for ($k = 0; $k < count($this->usercourse[$i]); $k++) {

//foreach ($this->usercourse[$i][0] as $key=>$value):
                                    //  echo $key." ".$value ."<br />";
//endforeach;
                                    ?>
                                    <a href="<?php echo $this->baseUrl() ?>/Courses/open/id/<?php echo $this->usercourse[$i][$k]['id']; ?>"><?php echo $this->usercourse[$i][$k]['title']; ?></a>
                                    <br>





                                    <?php
                                }
                            }
                        } else {
                            echo "no courses yet";
                        }
                        ?>


                    </div>
                </div></div>

    </html>
    <?php
} else {
    ?>
    <div class="Container">
        <div class="panel  col-md-5  col-md-offset-4 warning_alert ">
            <div class="panel-heading "> <h1><center>Not Permitted!!</center></h1></div>
        </div>
    </div>
    <?php
}
?>