

<?php
$auth = Zend_Auth::getInstance();
$storage = $auth->getStorage();
$sessionRead = $storage->read();
if (empty($sessionRead)) {
    ?>
    <html>
        <head>
            <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
            <link rel="stylesheet" href="style.css">
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
            <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
            <style>
                .form{

                    margin-top: 100px;


                }   
                .div{

                    width:100px;
                }    


            </style>
            <script>
                $(document).ready(function () {
                    $('#facebook').click(function () {
                        window.location.replace('../facebook/facebookauth');
                    });



                });
            </script>
        </head>
        <button class="btn-primary" id="facebook">Facebook</button>
        <button class="btn-info" id="twitter">twitter</button>
        <button class="btn-success" id="google">Google</button>

        <div class="container form"> 
            <div class="row">
                <div class="col-md-5 col-md-offset-4">
                    <div class="panel panel-primary " >
                        <div class="panel-heading" id="alert">
                            <h3 class="panel-title">Login</h3>
                        </div>
                        <div class="panel-body">

                            <!--//////////////////////////////////////////////-->
<!--                            <div id="fb-root"></div>
                            <script>(function (d, s, id) {
                                    var js, fjs = d.getElementsByTagName(s)[0];
                                    if (d.getElementById(id))
                                        return;
                                    js = d.createElement(s);
                                    js.id = id;
                                    js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=832576520158814&version=v2.0";
                                    fjs.parentNode.insertBefore(js, fjs);
                                    
                                }(document, 'script', 'facebook-jssdk'));</script>

                            <div class="fb-login-button" data-max-rows="1" data-size="medium" data-show-faces="false" data-auto-logout-link="false"></div>-->


                            <!--/////////////////////////////-->
                            <?php
                            echo $this->form;
                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </html>
    <?php
} else {
    header("Location: http://localhost/The-A-Team/public/home/home");
}
?>
