<!--<script>
$(document).ready(function(){
    
});

</script>-->
    


<div class="container">
<h3> Requests </h3>
</div>
<?php
for($i = 0; $i<count($this->requests); $i++){
?>
<div class="container">
    <div class="panel panel-primary">
        <div class="panel-body">
<img src="../../public/images/users/<?php echo $this->requests[$i]['image'];?>" class="img-circle" height="30px" width="30px">
<bt>
 <?php echo $this->requests[$i]['username'];?>
 <br>
 
     <?php echo $this->requests[$i]['desc'];?>


<br>
<?php if($this->user== $this->requests[$i]['User_Id']){?>
<a href="<?php echo $this->baseUrl()?>/Requests/edit/id/<?php echo $this->requests[$i]['id'];?>"  class="btn btn-info btn-xs"> Edit </a>
<a href="<?php echo $this->baseUrl()?>/Requests/delete/id/<?php echo $this->requests[$i]['id'];?>" class="btn btn-info btn-xs"> Delete </a>
<br />
<?php }?>
        </div>
</div>
</div>
<?php

}
?>
<div class="container">
<a href="<?php echo $this->baseUrl()?>/Requests/add" class="btn btn-info">addRequest </a>
</div>