<br /><br />
<script>
$(document).ready(function(){
    $('#edituser').click(function(){
        alert('here');
        window.location.replace('http://localhost/The-A-Team/public/control-room/admin');
    });
    
});
</script>
<center>
<div id="view-content">
	<p>View script for controller <b>ControlRoom</b> and script/action name <b>edituser</b></p>
        <?php
        echo $this->myform;
        ?>
</div>
   </center>