
<?php
$auth = Zend_Auth::getInstance();
$storage = $auth->getStorage();
$sessionRead = $storage->read();
$type = $sessionRead->type;
if ($type == "Admin") {
    ?>
    <br /><br />
    <script>
        $(document).ready(function () {
            $('#edituser').click(function () {
                window.location.replace('admin');             

        });
    </script>
    <center>
        <div id="view-content">
            <p>View script for controller <b>ControlRoom</b> and script/action name <b>edituser</b></p>
            <?php
            echo $this->myform;
            ?>
        </div>
    </center>
    <?php
} else {
    ?>
    <div class="Container">
        <div class="panel  col-md-5  col-md-offset-4 warning_alert ">
            <div class="panel-heading "> <h1><center>Not Permitted!!</center></h1></div>
        </div>
    </div>
    <?php
}
?>

