<?php
$auth = Zend_Auth::getInstance();
$storage = $auth->getStorage();
$sessionRead = $storage->read();
$type = $sessionRead->type;
if ($type == "Admin") {
?>
<script>
    $(document).ready(function () {
        
        $('#submit').click(function () {
            if($('#bdoy').val()=='' ){
                
            alert("Failed to save");
        }else{
                window.location.replace('admin');             }
        });
    });
</script>
<style> 
    
    .table-hover td,th{
        text-align: center;
        width: 200px;
        height:50px;
    }
    td{
        text-align: center; 
    }
</style>
<br /><br />
<div class="container">
      <a href="<?php echo $this->baseUrl() ?>/control-room/admin " id="alert" class="btn">Back To Settings</a>

<center>
<div id="view-content">
   <?php
   echo $this->form;
   ?>
</div>
    </center>
</div>
<?php
} else {
    ?>
    <div class="Container">
        <div class="panel  col-md-5  col-md-offset-4 warning_alert ">
            <div class="panel-heading "> <h1><center>Not Permitted!!</center></h1></div>
        </div>
    </div>
    <?php
}
?>
