<script>
//    $(document).ready(function () {
//        var parameter = window.location.search.replace("?", ""); // will return the GET parameter 
//        var values = parameter.split("=");
//        // will return and array as ["name", "sample"] 
//        
//        
//        $('#submit').click(function () {
//            alert($('#name').val());
//            if($('#name').val()!=='' ){
//            $.ajax({
//                url: "http://localhost/The-A-Team/public/control-room/admin",
//              type:"POST",
//              dataType:'json',
//            data: {
//                    process:'editcategory',
//                    id:values[1],
//                    name:$('#name').val(),
//                    
//                    
//                },
//                success : function(){
//                    
//                }
//                
//            });
//            window.location.replace('admin');
//        }else{
//            alert("Failed to save");
//        }
//        });
//    });
    $(document).ready(function () {
       
        $('#submit').click(function () {

            if ($('#name').val() == '') {

                alert("Failed to save");
            }else{
                window.location.replace('admin');             }
        });
    });
</script>
<style> 

    .table-hover td,th{
        text-align: center;
        width: 200px;
        height:50px;
    }
    td{
        text-align: center; 
    }
</style>
<br /><br />
  <center>
<div id="view-content">
   <?php
   echo $this->form;
   ?>
</div>
    </center>