<!--<div id="fb-root"></div>
<script>(function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id))
            return;
        js = d.createElement(s);
        js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=832576520158814&version=v2.0";
        fjs.parentNode.insertBefore(js, fjs);

    }(document, 'script', 'facebook-jssdk'));
    FB.login(checkLoginStatus, {scope: 'email, user_likes'});

    function checkLoginStatus(response) {
        if (!response || response.status !== 'connected') {
            alert('User is not authorized');
            document.getElementById('loginButton').style.display = 'block';
        } else {
            alert('User is authorized');
            document.getElementById('loginButton').style.display = 'none';
            console.log('Access Token: ' + response.authResponse.accessToken);

            //This has to be in your callback!
            var uid = response.authResponse.userID;
            var accessToken = response.authResponse.accessToken;

            testAPI();
            getFBData();
        }
    }
    }


    function testAPI() {
        console.log('Welcome!  Fetching your information.... ');
        FB.api('/me', function (response) {
            console.log('Good to see you, ' + response.name + '.' + response.id);
        });
    }
    ;

    function getFBData() {
        FB.api('/me', function (data) {
            alert(data.first_name + data.last_name + data.id);
        })
    }
    ;
    function fbLogout() {
        FB.logout(function (response) {
            //window.location.replace("http://stackoverflow.com"); is a redirect
            window.location.reload();
        });
    }

</script>

<div class="fb-login-button" data-max-rows="1" data-size="medium" data-show-faces="false" data-auto-logout-link="false"></div>
<br /><br />
<div id="view-content">
    <p>View script for controller <b>Facebook</b> and script/action name <b>facebookauth</b></p>


</div>-->



<!--////////////////////////////-->



<!DOCTYPE html>
<html>
    <head>
        
        <meta charset="UTF-8">
    </head>
    <body>
        
        <script>
            // This is called with the results from from FB.getLoginStatus().
            function statusChangeCallback(response) {
                console.log('statusChangeCallback');
                console.log(response);
                // The response object is returned with a status field that lets the
                // app know the current login status of the person.
                // Full docs on the response object can be found in the documentation
                // for FB.getLoginStatus().
                if (response.status === 'connected') {
                    // Logged into your app and Facebook.
                    testAPI();
                    
//                    window.location.replace('../home/home');

                } else if (response.status === 'not_authorized') {
                    // The person is logged into Facebook, but not your app.
                    document.getElementById('status').innerHTML = 'Please log ' +
                            'into this app.';
                    document.getElementById('facebooky').removeAttribute('hidden');

                    setInterval(function () {
                        testAPI();
                    }, 3000);
                } else {
                    // The person is not logged into Facebook, so we're not sure if
                    // they are logged into this app or not.
                    document.getElementById('status').innerHTML = 'Please log into Facebook.';
                    document.getElementById('facebooky').removeAttribute('hidden');
                    setInterval(function () {
                        testAPI();

                    }, 6000);
                }
            }

            // This function is called when someone finishes with the Login
            // Button.  See the onlogin handler attached to it in the sample
            // code below.
            function checkLoginState() {
                FB.getLoginStatus(function (response) {
                    statusChangeCallback(response);
                });
            }

            window.fbAsyncInit = function () {
                FB.init({
                    appId: '832576520158814',
                    cookie: true, // enable cookies to allow the server to access 
                    // the session
                    xfbml: true, // parse social plugins on this page
                    version: 'v2.2' // use version 2.2
                });

                // Now that we've initialized the JavaScript SDK, we call // FB.getLoginStatus().  This function gets the state of the
                // person visiting this page and can return one of three states to// the callback you provide.  They can be:
                // 1. Logged into your app ('connected')
                // 2. Logged into Facebook, but not your app ('not_authorized')
                // 3. Not logged into Facebook and can't tell if they are logged into your app or not.
                // These three cases are handled in the callback function.

                FB.getLoginStatus(function (response) {
                    statusChangeCallback(response);
                });

            };
            
            // Load the SDK asynchronously
            (function (d, s, id) {
                var js, fjs = d.getElementsByTagName(s)[0];
                if (d.getElementById(id))
                    return;
                js = d.createElement(s);
                js.id = id;

                //    js.src = "//connect.facebook.net/en_US/sdk.js";
                js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=832576520158814&version=v2.0";

                fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));

            // Here we run a very simple test of the Graph API after login is
            // successful.  See statusChangeCallback() for when this call is made.
            function testAPI() {
//                alert('Welcome!  Fetching your information.... ');
                FB.api('/me', function (response) {
//                    alert('Successful login for: ' + response.name);
                    document.getElementById('name').value =
                            response.name;
                    document.getElementById('facebookid').value =
                            response.id;
                    document.getElementById('gender').value =
                            response.gender;
                    document.getElementById('country').value =
                            response.locale;
                   

                });

            }
        </script>

        <!--
          Below we include the Login Button social plugin. This button uses
          the JavaScript SDK to present a graphical Login button that triggers
          the FB.login() function when clicked.
        -->

    <fb:login-button scope="first_name,gender,id,email,country" onlogin="checkLoginState();">
    </fb:login-button>
    <div id="status">
        <?php
        echo $this->log;
        ?>
    </div>
    
    <div id="facebooky"  hidden>
        <div  class="fb-login-button" data-max-rows="1" data-size="medium" data-show-faces="false" data-auto-logout-link="false"  ></div>
    </div>
</body>
</html>