<script>
$(document).ready(function(){
//    $.get('/social/facebookauth/', getFacebookAuthReady);
//    
//    
//    function getFacebookAuthReady(response) {
// 
//    var ar_response = response.split("|");
//    var responseCode = ar_response[0];
//    var responseText = ar_response[1];
// 
//    if (responseCode == 1)
//    {
//        // Go to URL for Facebook Authorization
//        window.location.href=responseText;
//    }
//    else
//    {
//        // Show error
//        ...
//    }
}



});

</script>
<br /><br />
<div id="view-content">
	<p>View script for controller <b>Facebook</b> and script/action name <b>facebookauth</b></p>
        
        <?php
        echo $mess;
        ?>
</div>