<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link rel="stylesheet" href= "../../../public/bootstrap-3.3.2-dist/css/bootstrap.css"> 
        <link rel="stylesheet" href= "../../../public/bootstrap-3.3.2-dist/css/bootstrap-theme.css"> 
        <script src="../../../public/jquery-2.1.3.min.js" type="text/javascript"></script>
        <script src="../../../public/bootstrap-3.3.2-dist/js/bootstrap.js" type="text/javascript"></script>

                <?php echo $this->headMeta(); ?>
                <?php echo $this->headTitle() ?>
                <?php echo $this->headLink() ?>
                <?php echo $this->headScript() ?>
                </head>
                <body>
                    <nav class="navbar navbar-inverse">
                        <div class="container-fluid">
                            <div class="navbar-header"> </div>

                            <div>

                                <ul class="nav navbar-nav">
                                    <li class="active"><a  navbar-brand href="#"></a></li>
                                    <li><a href="#"></a></li>
                                </ul>
                            </div>
                        </div>
                    </nav>
                    <div id="header-navigation" style="float: right">
                        
                    </div>
                    </div>

                    <?php echo $this->layout()->content ?>

                </body>
                </html>

