
<html >
    <head>
         <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?php echo $this->headLink()->appendStylesheet('/css/bootstrap.css') ?>
        <?php echo $this->headLink()->appendStylesheet('/css/bootstrap-theme.css') ?>
        <?php echo $this->headScript()->appendFile('/js/jquery-2.1.3.min.js.js') ?>
        <?php echo $this->headScript()->appendFile('/js/bootstrap.js') ?>
    </head>
    <body>


        <?php echo $this->layout()->content ?>

    </body>
</html>

