
<html >
    <head>
         <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?php echo $this->headLink()->appendStylesheet('/bootstrap-3.3.2-dist/css/bootstrap.css') ?>
        <?php echo $this->headLink()->appendStylesheet('/bootstrap-3.3.2-dist/css/bootstrap-theme.css') ?>
        <?php echo $this->headScript()->appendFile('/jquery-2.1.3.min.js') ?>
        <?php echo $this->headScript()->appendFile('/bootstrap-3.3.2-dist/js/bootstrap.js') ?>
    </head>
    <body>
<!--     <ul class="nav nav-pills">
  <li role="presentation" class="active"><a href="#">Home</a></li>
  <li role="presentation"><a href="#">Profile</a></li>
  <li role="presentation"><a href="#">Messages</a></li>
</ul>-->

        <?php echo $this->layout()->content ?>

    </body>
</html>

