
<html>
    <head>
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script src ="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
        <script src="../../../../public/js/openMaterial.js"></script>
        <style> 
            #addMaterialForm, #addMaterial_btn {
                padding: 5px;
                text-align: center;
                border: solid 1px ;
            }

            #addMateriaForm {
                padding: 50px;
                display: none;
            }
            #alert, #addMaterial_btn{
                background-color:#123456; 
                color: #FFFFFF;
            }
        </style>
    </head> 
    <body>
        <div class="container">

            <div class="row">
                <div class=" col-md-5 jumbotron alert alert-info" id="alert">
                    <h2> <?php echo $this->title; ?> </h2>
                </div>

                <div class="col-md-3 pull-right">

                    <img src="../../../../public/images/users/<?php echo $this->user_image; ?>"

                         class="img-responsive img-rounded"  width="120px" height="120px">
                </div>


                <div class="col-md-1 pull-right" >
                    <h4 class="title"> Instructor: </h4>
                    <?php echo $this->user_name; ?>
                </div>
            </div>


            <div class="row">
                <div class=" col-md-3 panel panel-primary">
                    <div class="panel-body">
                        <h5 class="title"> Course Start:   <?php echo $this->startdate; ?> </h5>
                        <h5 class="title"> Duration:    <?php echo $this->duration; ?> weeks</h5>
                    </div>
                </div>
                <?php
                //check if the student have this course or not
                $currentUser_id = 2;

                $currentUser_model = new Application_Model_UserCourse();
                $all_courses = $currentUser_model->selectUserCourseByUserId($currentUser_id);
                $flage = 0;
                for ($i = 0; $i < count($all_courses); $i++) {
                    if ($all_courses[$i]['Course_Id'] == $this->course_id) {
                        $flage = 1;
                    }
                }
                if ($flage == 0) {
                    ?>
                    <button type="button" class="btn btn-primary pull-right" id="join" 
                            onclick="Join('<?php echo $currentUser_id; ?>', '<?php echo $this->course_id; ?>')">Join Course</button>
                            <?php
                        } else {
                            ?>
                    <button type="button" class="btn btn-primary pull-right" id="join" 
                            onclick="Join('<?php echo $currentUser_id; ?>', '<?php echo $this->course_id; ?>')">UnJoin Course</button>
                            <?php
                        }
                        ?>
            </div>



            <div class="row">
                <div class=" panel panel-primary">
                    <div class="panel-body">
                        <h4 class="title">About Course:</h4></br>
                        <?php echo $this->desc; ?> 
                    </div>
                </div>
            </div>

            <?php
            //check if the instructor have this course or not
            $currentUser_id = 1;

            $currentUser_model = new Application_Model_UserCourse();
            $all_courses = $currentUser_model->selectUserCourseByUserId($currentUser_id);
            $flage_instructor = 0;
            for ($i = 0; $i < count($all_courses); $i++) {
                if ($all_courses[$i]['Course_Id'] == $this->course_id) {
                    $flage_instructor = 1;
                }
            }

            if ($flage_instructor == 1) {
                ?>
                <div class="row col-md-offset-0">
                    <button type="button" class="btn btn-primary" id="addMaterial_btn">Add Materials</button></br>
                    <div class="row  col-md-6 panel panel-info" id="addMateriaForm">
                        <?php echo $this->addMaterial_form; ?>
                    </div>
                </div>
                <?php
            }
            ?>

            <div class="col-md-5">
                <?php
                if ($this->material_info) {
                    for ($i = 0; $i < count($this->arr_types_id); $i++) {
                        ?>

                        <div class="row">
                            <div class=" panel panel-primary">
                                <div class="panel-body">
                                    <?php
                                    $type_model = new Application_Model_Types();
                                    $type_info = $type_model->selectTypeById($this->arr_types_id[$i]);
                                    echo "<h4 class='title'>" . $type_info[0]['name'] . "</h4> </br>";

                                    $matrial_model = new Application_Model_Materials();
                                    $matrial_info = $matrial_model->selectMaterialByCourseId_TypeId($this->course_id, $this->arr_types_id[$i]);

                                    for ($j = 0; $j < count($matrial_info); $j++) {
                                        ?>
                                        <a class="list-group-item-info"  href="<?php echo $this->baseUrl() ?>/Courses/show/id/<?php echo $matrial_info[$j]['id']; ?>"><?php echo $matrial_info[$j]['name']; ?> </a>
                                        <?php
                                        if($flage_instructor){
                                        ?>
                                        <a class="btn pull-right col-md-1" id="alert" href="<?php echo $this->baseUrl() ?>/Courses/delete/id/<?php echo $matrial_info[$j]['id']; ?>/courseid/<?php echo $this->course_id; ?>">x</a></br></br>
                                        <?php
                                        }else{
                                            echo"</br></br>";
                                        }
                                    }
                                    ?>
                                </div>
                            </div>
                        </div>

                        <?php
                    }
                } else {
                    echo "No Materials yet!!";
                }
                ?>
            </div>




            <div class="col-md-6  ">
                <div class=" col-md-offset-5 alert alert-info" id="alert">
                    <h5><center> Related Courses </center> </h5>
                </div>
                <div class="col-md-offset-5 panel panel-primary" >
                    <?php
                    for ($i = 0; $i < count($this->arr_tags_id); $i++) {
                        $courseTag_model = new Application_Model_CourseTag();

                        $relatedCourses_ids = $courseTag_model->getCourseTagByTagId($this->arr_tags_id[$i]);
                        for ($j = 0; $j < count($relatedCourses_ids); $j++) {

                            //for related courses not this course
                            if ($relatedCourses_ids[$j]["courseid"] != $this->course_id) {
                                $relatedCourse_model = new Application_Model_Courses();
                                $relatedCourse_info = $relatedCourse_model->getCourseById($relatedCourses_ids[$j]["courseid"]);
                                ?>
                                <center><a  class="list-group-item-info" href="<?php echo $this->baseUrl() ?>/Courses/open/id/<?php echo $relatedCourses_ids[$j]["courseid"]; ?>"><?php echo $relatedCourse_info[0]['title']; ?> </a></center></br>
                                    <?php
                                }
                            }
                        }
                        ?>
                </div>
            </div>

        </div> 

    </body>
</html>
