<html>
    <head>
    
        
        
        
        
        
    </head>
    <body>



<div class="container">
    <h3> Answers </h3>
</div>
<?php
for ($i = 0; $i < count($this->requests); $i++) {
    ?>
    <div class="container">
        <div class="panel panel-primary">
            <div class="panel-body" id="Request_<?php echo $this->requests[$i]['id']?>">
                <img src="../../public/images/users/<?php echo $this->requests[$i]['image']; ?>" class="img-circle" height="30px" width="30px">
                <bt>
                    <?php echo $this->requests[$i]['username']; ?>
                    <br>
<p id="<?php echo $this->requests[$i]['id']; ?>"> <?php  echo $this->requests[$i]['desc']; ?></p>
                   


                    <br>
                    <?php
                    $auth = Zend_Auth::getInstance();
                    $storage = $auth->getStorage();
                    $sessionRead = $storage->read();
                    $type = $sessionRead->type;
                    if ($type == "Instructor" || $type == "Student") {

                        if ($this->user == $this->requests[$i]['User_Id']) {
                            ?>
                            <a   class="btn btn-info btn-xs pull-right"onclick="editRequest(<?php echo $this->requests[$i]['id']; ?>)"> Edit </a>
                            <a href="<?php echo $this->baseUrl() ?>/Requests/delete/id/<?php echo $this->requests[$i]['id']; ?>" class="btn btn-info btn-xs pull-right"> Delete </a>
                            <br />
                            <?php
                        }
                    } else {
                        ?>
                        <a href="<?php echo $this->baseUrl() ?>/Requests/delete/id/<?php echo $this->requests[$i]['id']; ?>" class="btn btn-info btn-xs pull-right"> Delete </a>
                        <?php
                    }
                    ?>

            </div>
        </div>
    </div>
    <?php
    }
        $auth = Zend_Auth::getInstance();
        $storage = $auth->getStorage();
        $sessionRead = $storage->read();
        $type = $sessionRead->type;
    if ($type == "Instructor" || $type == "Student") {
        ?>
        <div class="container">
            <!--<a href="<?php echo $this->baseUrl() ?>/Requests/add" class="btn btn-info">addRequest </a>-->
            
            <?php
echo $this->form;
?>
        </div>
        <?php
}
?>
        
        <script>
        
       
            /**
             * this function to submit the text of comment after edit it
             * @returns {undefined}
             */

            function add(id) {
                //get the body of the comment after edit it
                var body_edit = document.getElementById("bodyEdit_" + id);
                console.log(body_edit.value);

                //open http request to send the parameters of comment to update
                var xmlhttp = new XMLHttpRequest();
                xmlhttp.open("POST", "http://localhost/The-A-Team/public/Requests/edit/", true);
                xmlhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
                xmlhttp.send("id=" + id + "&desc=" + body_edit.value );

                //on change check even the request send or not


                xmlhttp.onreadystatechange = function () {

                    // alert(xmlhttp.readyState);
                    // alert(xmlhttp.status);
                    if (xmlhttp.readyState === 4 && xmlhttp.status === 200) {
                    }
                    console.log(xmlhttp.responseText);

                    //append the comment after update
                    var request_parent = document.getElementById("Request_" + id);
                    
                    var request_after_edit=document.createElement("p");
                    request_after_edit.setAttribute("id",id);
                    request_after_edit.innerHTML=body_edit.value;
                    
                     body_edit.remove();
                    var button_after_edit = document.getElementById("btn_" + id);
                    button_after_edit.remove();
                    
                    request_parent.appendChild(request_after_edit);
                };
            }
            /**
             * this function to edit the Comment
             * @returns {undefined}
             */
            function editRequest(id) {

                //get the body of the comment and remove it
                var Request = document.getElementById(id);
                var Request_body = Request.innerHTML;
                Request.remove();

                //create a text field by the body of the comment 
                var textfield = document.createElement("input");
                textfield.setAttribute("type", "text");
                textfield.setAttribute("class","form-control");
                textfield.setAttribute("value", Request_body);
                textfield.setAttribute("id", "bodyEdit_" + id);

                //create add button to add the comment
                var button = document.createElement("button");
                button.setAttribute("class", "btn btn-primary");
                button.setAttribute("id", "btn_"+ id);
                button.innerHTML="Add";
                button.setAttribute("onclick", "add("+id+")");

                //append the text area to the parent
                var request_parent = document.getElementById("Request_" + id);

                request_parent.appendChild(textfield);
                request_parent.appendChild(button);

            }
            
            

 
        
        
        
        </script>
    </body></html>